# Generated by Django 5.2.17 on 2026-09-16 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('message', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('book_wanted', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.book')),
                ('offered_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='catalog.book')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['requester', 'status'], name='trade_requester_status_idx'), models.Index(fields=['book_wanted', 'status'], name='trade_wanted_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('book_wanted', 'offered_book'), name='unique_pending_trade_offer', violation_error_message='This book has already been offered for that listing.'), models.CheckConstraint(condition=models.Q(('book_wanted', models.F('offered_book')), _negated=True), name='trade_books_differ', violation_error_message='A book cannot be swapped for itself.')],
            },
        ),
    ]
